name: Windows Test

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # You can specify a version like '3.10' if needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-html  # Ensure pytest-html is installed

    - name: Run tests and generate HTML report
      run: |
        pytest tests/test_sample.py tests/test_api.py --html=report.html

    - name: Upload HTML report
      uses: actions/upload-artifact@v4
      with:
        name: pytest-report
        path: report.html